# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packedinfo.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'packedinfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10packedinfo.proto\x12\x0c\x61pp.protobuf\"{\n\nPackedInfo\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0f\n\x07version\x18\x02 \x01(\r\x12&\n\x05image\x18\x03 \x01(\x0b\x32\x17.app.protobuf.ImageHash\x12&\n\x05video\x18\x04 \x01(\x0b\x32\x17.app.protobuf.VideoHash\"\x18\n\tImageHash\x12\x0b\n\x03md5\x18\x04 \x01(\t\"\x18\n\tVideoHash\x12\x0b\n\x03md5\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packedinfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKEDINFO']._serialized_start=34
  _globals['_PACKEDINFO']._serialized_end=157
  _globals['_IMAGEHASH']._serialized_start=159
  _globals['_IMAGEHASH']._serialized_end=183
  _globals['_VIDEOHASH']._serialized_start=185
  _globals['_VIDEOHASH']._serialized_end=209
# @@protoc_insertion_point(module_scope)
